name: OWASP Dependency-Check and SonarCloud SAST Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Run OWASP Dependency-Check
        run: mvn dependency-check:check

      - name: Upload OWASP Dependency-Check report
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html
          
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          scan-ref: '.'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          output: 'trivy-results.json'
  
      - name: update report
        uses: actions/upload-artifact@v2
        with:
          name: trivy-report
          path: trivy-results.json

      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.projectKey=manager_productmanager -Dsonar.organization=manager -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=3fae20ba4d454b4fc80ef036566468a5ba228829
