name: OWASP Dependency-Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Run OWASP Dependency-Check
        run: |
          docker run --rm -v $(pwd):/workdir owasp/dependency-check:6.2.2 \
          --scan /github/workspace/target \
          --format HTML \
          --output /github/workspace/dependency-check-report.html

      - name: Upload OWASP Dependency-Check report
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-report
          path: dependency-check-report.html
